// SSCP sub-objective tag per question, in the same order as questions.js.
// IDs follow the standard SSCP CBK domain/sub-objective structure (best-effort
// mapping — adjust freely if your practice-exam tool uses a different outline).
window.TOPICS = [
  "1.2 Security concepts (CIA/AAA)",
  "1.1 ISC2 Code of Ethics",
  "1.3 Policies, standards, procedures, guidelines",
  "1.3 Policies, standards, procedures, guidelines",
  "1.3 Policies, standards, procedures, guidelines",
  "1.2 Least privilege",
  "1.2 Separation of duties",
  "1.2 Dual control / two-person integrity",
  "1.2 Mandatory vacation",
  "1.2 Job rotation",
  "1.6 Security awareness and training",
  "1.6 Security awareness and training",
  "1.3 Acceptable use policy",
  "1.4 Asset classification and labeling",
  "1.4 Data owner role",
  "1.4 Data custodian role",
  "1.5 Change management",
  "1.5 Configuration management",
  "1.5 Secure baselines and hardening",
  "1.7 Physical access controls",
  "1.6 Security awareness and training",
  "1.6 Background checks and personnel screening",
  "1.6 Onboarding / offboarding processes",
  "1.7 Physical intrusion detection",
  "1.7 Fire suppression and environmental controls",
  "1.3 Control objectives",
  "1.2 Defense in depth",
  "1.3 Control categories (admin/tech/physical)",
  "1.3 Control categories (admin/tech/physical)",
  "1.3 Control functions (deterrent/preventive/detective/corrective)",
  "1.3 Control functions (deterrent/preventive/detective/corrective)",
  "1.3 Control functions (deterrent/preventive/detective/corrective)",
  "1.3 Compensating controls",
  "1.4 Records retention and destruction",
  "1.4 Media disposal and sanitization",
  "1.4 Data labeling",
  "1.4 Asset inventory and management",
  "1.2 Separation of duties",
  "1.3 Senior management responsibility",
  "1.3 NDA and contractual agreements",

  "2.1 Identification vs authentication",
  "2.1 Accountability and auditing (AAA)",
  "2.1 Authentication factors",
  "2.1 Multi-factor authentication",
  "2.1 Biometric error rates (FAR/FRR/CER)",
  "2.1 Biometric error rates (FAR/FRR/CER)",
  "2.1 Kerberos",
  "2.1 RADIUS",
  "2.1 RADIUS vs TACACS+",
  "2.2 LDAP and directory services",
  "2.2 SAML and federated SSO",
  "2.2 OAuth 2.0",
  "2.2 OpenID Connect",
  "2.1 Password weaknesses",
  "2.1 Secure password storage (hashing)",
  "2.3 Service accounts and credential management",
  "2.2 Identity federation",
  "2.3 Access reviews and recertification",
  "2.4 Privileged Access Management",
  "2.1 Online password attack defenses",
  "2.1 Account lockout",
  "2.2 Single Sign-On (SSO)",
  "2.2 SSO security risks",
  "2.4 Just-in-time access",
  "2.4 Need-to-know",
  "2.1 TOTP / OTP tokens",
  "2.1 HOTP vs TOTP",
  "2.1 FIDO2 / phishing-resistant MFA",
  "2.3 Joiner-mover-leaver / de-provisioning",
  "2.4 Access control matrix / ACL / capability list",
  "2.4 Access control lists (ACLs)",
  "2.3 Identity provisioning automation",
  "2.1 Phishing-resistant authentication",
  "2.4 Role-Based Access Control (RBAC)",
  "2.4 Mandatory Access Control (MAC)",
  "2.4 Discretionary Access Control (DAC)",
  "2.4 Attribute-Based Access Control (ABAC)",
  "2.4 Rule-Based Access Control",

  "3.1 Risk concepts and definitions",
  "3.1 Vulnerabilities",
  "3.1 Threats and threat agents",
  "3.1 Quantitative vs qualitative analysis",
  "3.1 ALE / SLE / ARO formulas",
  "3.1 ALE / SLE / ARO formulas",
  "3.1 ALE / SLE / ARO formulas",
  "3.1 Risk treatment - acceptance",
  "3.1 Risk treatment - transference",
  "3.1 Risk treatment - avoidance",
  "3.1 Risk treatment - mitigation",
  "3.1 Risk register",
  "3.3 Vulnerability scanning",
  "3.3 Vulnerability scanning vs penetration testing",
  "3.3 Penetration test authorization",
  "3.3 White-box / black-box testing",
  "3.3 White-box / black-box testing",
  "3.3 Vulnerability management process",
  "3.3 CVSS scoring",
  "3.3 CVE identifiers",
  "3.4 Logging and audit trails",
  "3.4 Central log management",
  "3.4 Indicators of compromise (IOC)",
  "3.1 Key risk indicators (KRI)",
  "3.4 SIEM",
  "3.4 Anomaly-based detection",
  "3.4 Signature-based detection",
  "3.4 Continuous monitoring",
  "3.4 Log integrity and tamper resistance",
  "3.4 Baseline monitoring",
  "3.4 Alert fatigue and detection tuning",
  "3.1 Control effectiveness metrics",
  "3.3 External penetration testing",
  "3.3 Vulnerability prioritization",
  "3.4 Threat intelligence",
  "3.3 Control validation and assessment",
  "3.1 Risk appetite",

  "4.1 Incident response lifecycle (NIST)",
  "4.1 Incident containment",
  "4.1 Post-incident activity / lessons learned",
  "4.1 Incident eradication",
  "4.2 Order of volatility",
  "4.2 Chain of custody",
  "4.2 Forensic hashing and integrity",
  "4.2 Computer forensics fundamentals",
  "4.2 Write-blockers and evidence preservation",
  "4.3 Business Continuity Plan (BCP)",
  "4.3 Disaster Recovery Plan (DRP)",
  "4.3 Business Impact Analysis (BIA)",
  "4.3 RTO",
  "4.3 RPO",
  "4.3 MTD",
  "4.3 WRT",
  "4.3 Backup types (full)",
  "4.3 Backup types (incremental)",
  "4.3 Backup types (differential)",
  "4.3 Alternate sites (hot)",
  "4.3 Alternate sites (cold)",
  "4.3 Alternate sites (warm)",
  "4.3 BCP/DRP testing - tabletop",
  "4.3 BCP/DRP testing - full interruption",
  "4.3 BCP/DRP testing - parallel",
  "4.1 Incident definition",
  "4.1 Initial incident response actions",
  "4.1 CSIRT / IRT roles",
  "4.1 Lessons learned purpose",
  "4.1 Eradication confirmation",
  "4.1 Incident communications",
  "4.2 Forensic evidence handling risks",
  "4.3 Immutable / air-gapped backups",
  "4.3 BCP/DRP testing - restoration",
  "4.1 Reconstitution and recovery",
  "4.2 Compromised system handling",

  "5.1 Symmetric cryptography",
  "5.1 AES",
  "5.1 AES key lengths",
  "5.1 RSA / asymmetric algorithms",
  "5.1 Diffie-Hellman key exchange",
  "5.1 Elliptic Curve Cryptography (ECC)",
  "5.1 Hash function properties",
  "5.1 Hash function security (MD5/SHA-1 deprecation)",
  "5.1 SHA family output lengths",
  "5.1 Digital signatures - properties",
  "5.1 Digital signature verification",
  "5.4 Public Key Infrastructure (PKI)",
  "5.4 Certificate Authorities",
  "5.4 OCSP - certificate validation",
  "5.4 Certificate Revocation Lists (CRL)",
  "5.2 Key escrow and management",
  "5.3 IPsec",
  "5.3 IPsec - AH vs ESP",
  "5.3 TLS",
  "5.3 S/MIME and email cryptography",
  "5.1 Side-channel attacks",
  "5.1 Block cipher modes / IV",

  "6.1 OSI model - Transport layer",
  "6.1 OSI model - Network layer",
  "6.1 OSI model - Data Link layer",
  "6.1 TCP three-way handshake",
  "6.1 Common ports - HTTPS",
  "6.1 Common ports - SSH",
  "6.1 Common ports - Telnet",
  "6.1 DNS",
  "6.1 DHCP",
  "6.1 ARP",
  "6.2 ARP poisoning / MITM",
  "6.2 DoS / DDoS attacks",
  "6.2 Replay attacks",
  "6.5 Stateful firewalls",
  "6.5 Stateless packet filters",
  "6.5 Application / proxy firewalls",
  "6.5 Next-generation firewalls",
  "6.5 IDS vs IPS",
  "6.4 IPsec VPNs",
  "6.6 WEP weaknesses",
  "6.6 WPA3 / wireless security",
  "6.3 802.1X / port-based NAC",
  "6.4 VLANs",
  "6.3 Network access control",
  "6.1 Network devices (switch/router/hub)",
  "6.4 DMZ / screened subnet",
  "6.4 NAT",
  "6.5 Honeypots",
  "6.2 Man-in-the-middle attacks",
  "6.4 TLS as MITM defense",
  "6.2 DNSSEC",
  "6.4 SPF email authentication",
  "6.4 DKIM email signing",
  "6.4 DMARC",
  "6.4 Network segmentation",
  "6.2 DNS cache poisoning",
  "6.6 Bluetooth attacks - Bluejacking",
  "6.6 Bluetooth attacks - Bluesnarfing",
  "6.4 Network defense design",
  "6.4 Jump server / bastion host",
  "6.4 SFTP / FTPS secure file transfer",
  "6.4 Zero trust networking",
  "6.6 Rogue access point defense",
  "6.2 SYN flood / DoS defenses",

  "7.1 Malware - worms",
  "7.1 Malware - Trojans",
  "7.1 Malware - rootkits",
  "7.1 Ransomware",
  "7.1 Spyware",
  "7.1 Sandboxing",
  "7.2 Endpoint Detection and Response (EDR)",
  "7.2 Cross-site scripting (XSS)",
  "7.2 CSRF",
  "7.2 SQL injection defenses",
  "7.2 Buffer overflows",
  "7.2 Input validation",
  "7.2 Secure coding standards",
  "7.2 Patch management",
  "7.2 OS hardening",
  "7.2 Application allowlisting",
  "7.2 SAST",
  "7.2 DAST",
  "7.2 Fuzz testing",
  "7.3 Mobile Device Management - remote wipe",
  "7.3 BYOD security risks",
  "7.3 Containerization / MAM",
  "7.4 Virtualization security",
  "7.4 Containers - definition",
  "7.4 Container security - shared kernel",
  "7.4 Container image supply chain",
  "7.2 Least functionality",
  "7.2 Full-disk encryption",
  "7.5 IoT security",
  "7.2 Secure baselines",
  "7.2 Code signing",
  "7.1 Logic bombs",
  "7.1 Advanced Persistent Threats (APT)",
  "7.1 Social engineering",
  "7.1 Phishing defenses",
  "7.2 Security through obscurity",
  "7.2 Least privilege for applications",
  "7.2 Secure SDLC requirements phase"
,
  "1.1 ISC2 Code of Ethics canons",
  "1.1 ISC2 Code of Ethics priority",
  "1.1 Code of Ethics complaint process",
  "1.7 CPTED",
  "1.7 Physical perimeter controls",
  "1.7 Visitor management",
  "1.7 Tailgating",
  "1.3 Clean desk policy",
  "1.7 Cable locks and port control",
  "1.4 Equipment lifecycle management",
  "1.4 NIST 800-88 sanitization categories",
  "1.4 Degaussing",
  "1.4 SSD sanitization challenge",
  "1.4 Data classification levels",
  "1.4 Data labeling standards",
  "1.4 Privacy: PII vs PHI vs PCI",
  "1.4 Privacy notice and consent",
  "1.3 Insider threat indicators",
  "1.3 Whistleblower protections",
  "1.2 Cross-training vs job rotation",
  "1.6 Onboarding steps",
  "1.6 Background check categories",
  "1.6 Drug testing policy",
  "1.3 RACI matrix",
  "1.3 Documentation hierarchy",
  "1.6 Security culture",
  "1.6 Awareness program metrics",
  "1.6 Phishing simulation",
  "1.6 Role-based training",
  "1.5 Vendor security assessments",
  "1.3 AUP violations response",
  "1.3 Conflict of interest",
  "1.4 Information classification ownership",
  "1.7 Tamper-evident seals",
  "1.7 Lock types",
  "1.2 Split knowledge vs dual control",
  "1.5 Maker-checker process",
  "1.3 Documentation review cadence",
  "1.5 Configuration drift",
  "1.5 Environment separation",
  "2.3 NIST IAL",
  "2.1 NIST AAL",
  "2.2 NIST FAL",
  "2.3 Identity proofing",
  "2.1 Knowledge-based authentication weakness",
  "2.4 Bell-LaPadula model",
  "2.4 Biba model",
  "2.4 Clark-Wilson model",
  "2.4 Brewer-Nash (Chinese Wall)",
  "2.4 Take-Grant model",
  "2.1 NIST 800-63B password guidance",
  "2.1 Password manager benefits",
  "2.1 Passwordless authentication",
  "2.1 Certificate-based authentication",
  "2.2 mTLS",
  "2.2 OAuth authorization code flow",
  "2.2 OAuth client credentials flow",
  "2.2 OAuth refresh tokens",
  "2.1 JWT structure",
  "2.1 JWT 'none' algorithm vulnerability",
  "2.3 Token revocation",
  "2.1 Hardware vs soft tokens",
  "2.1 SMS MFA weakness",
  "2.1 MFA prompt bombing",
  "2.3 Recovery codes",
  "2.1 Behavioral biometrics",
  "2.1 Continuous authentication",
  "2.1 Step-up authentication",
  "2.1 Account lockout settings",
  "2.4 Privileged account types",
  "2.1 Default account hardening",
  "2.4 Guest account risks",
  "2.4 Shared account risks",
  "2.3 Service account credential rotation",
  "2.3 IGA",
  "2.1 Authentication vs authorization",
  "2.3 IAL vs AAL",
  "3.3 CWE",
  "3.3 CCE",
  "3.3 CVSS components",
  "3.3 CVSS vector string",
  "3.3 EPSS",
  "3.3 KEV catalog",
  "3.3 Responsible disclosure",
  "3.3 Bug bounty programs",
  "3.3 Vulnerability disclosure timeline",
  "3.1 Risk matrix",
  "3.1 Risk owner",
  "3.1 Risk register elements",
  "3.1 ROSI",
  "3.1 NPV of security investment",
  "3.4 NIST CSF functions",
  "3.4 MITRE ATT&CK",
  "3.4 Cyber kill chain",
  "3.4 Diamond model",
  "3.4 STRIDE",
  "3.4 PASTA",
  "3.4 LINDDUN",
  "3.4 Attack trees",
  "3.4 Syslog severity levels",
  "3.2 Log retention requirements",
  "3.4 Log normalization",
  "3.4 Correlation rules",
  "3.4 SOAR purpose",
  "3.4 UEBA",
  "3.4 Threat hunting types",
  "3.4 MITRE ATT&CK terminology",
  "3.4 NetFlow vs packet capture",
  "3.4 Full packet capture use case",
  "3.4 STIX/TAXII",
  "3.4 Threat intel feeds",
  "3.4 Dwell time",
  "3.4 ISAC",
  "3.3 Coordinated vulnerability disclosure",
  "3.3 Vulnerability prioritization layer",
  "4.1 Incident severity classification",
  "4.1 IR SLA response times",
  "4.1 CSIRT vs SOC vs IRT",
  "4.1 War room",
  "4.1 ICS for incidents",
  "4.1 Tabletop facilitator",
  "4.1 After-action report contents",
  "4.3 US state breach notification laws",
  "4.3 GDPR breach notification timing",
  "4.3 HIPAA breach notification timing",
  "4.3 PCI breach response",
  "4.1 Law enforcement coordination",
  "4.2 Evidence types",
  "4.2 Spoliation",
  "4.2 Best evidence rule",
  "4.2 Hearsay exception for business records",
  "4.2 Static vs dynamic malware analysis",
  "4.2 Reverse engineering",
  "4.2 Memory forensics tooling",
  "4.2 Disk imaging tools",
  "4.2 Network forensics",
  "4.2 Mobile device forensics",
  "4.2 Cloud forensics challenges",
  "4.2 Affidavits in evidence",
  "4.2 Expert witness",
  "4.3 BIA outputs",
  "4.3 Dependencies mapping",
  "4.3 Single point of failure",
  "4.3 RAID types and recovery",
  "4.3 Snapshot vs backup",
  "4.3 Sync vs async replication",
  "4.3 GFS backup rotation",
  "4.3 Backup encryption",
  "4.3 Ransomware recovery",
  "5.1 Stream vs block ciphers",
  "5.1 ECB pitfall",
  "5.1 CBC mode",
  "5.1 GCM mode",
  "5.1 CTR mode",
  "5.1 AEAD ciphers",
  "5.1 Salt vs nonce vs IV",
  "5.1 KDFs",
  "5.1 HMAC vs hash",
  "5.1 MAC vs digital signature",
  "5.1 RSA recommended key sizes",
  "5.1 ECC named curves",
  "5.3 Forward secrecy",
  "5.3 TLS 1.3 improvements",
  "5.4 Certificate chain validation",
  "5.4 Root vs intermediate CA",
  "5.4 X.509 fields",
  "5.4 Wildcard certificates",
  "5.4 Certificate transparency",
  "5.1 Quantum-resistant algorithms",
  "5.1 Birthday attack",
  "5.1 Rainbow tables",
  "5.1 Padding oracle attack",
  "6.1 OSI Physical layer",
  "6.1 OSI Session layer",
  "6.1 OSI Presentation layer",
  "6.1 OSI Application layer",
  "6.1 TCP/IP 4-layer model",
  "6.1 TCP vs UDP",
  "6.1 ICMP and ping",
  "6.1 SMTP port",
  "6.1 DNS port",
  "6.1 SNMP port",
  "6.1 RDP port",
  "6.1 LDAP ports",
  "6.1 CIDR notation",
  "6.1 RFC 1918 private ranges",
  "6.1 IPv6 vs IPv4",
  "6.1 MAC address length",
  "6.2 VLAN hopping",
  "6.1 802.1Q trunking",
  "6.4 Spanning Tree Protocol",
  "6.1 OSPF and BGP",
  "6.2 BGP hijacking",
  "6.4 DoT and DoH",
  "6.1 Recursive vs authoritative DNS",
  "6.4 NetFlow vs sFlow",
  "6.5 Span port vs network tap",
  "6.4 Wireshark and tcpdump",
  "6.5 Proxy types",
  "6.4 CDN security",
  "6.5 Default deny rule order",
  "6.4 VPN types",
  "6.4 Split tunneling risk",
  "6.6 WPA2-Enterprise vs PSK",
  "6.6 EAP variants",
  "6.6 Wireless site survey",
  "6.6 Evil twin attack",
  "6.6 KRACK attack",
  "7.1 Drive-by download",
  "7.1 Watering hole attack",
  "7.1 USB drop attack",
  "7.1 Supply chain attack",
  "7.1 Polymorphic vs metamorphic malware",
  "7.1 Fileless malware",
  "7.2 Heuristic vs signature AV",
  "7.2 Behavioral analysis",
  "7.2 DEP / NX",
  "7.2 ASLR",
  "7.2 Stack canaries",
  "7.2 ROP attacks",
  "7.2 Format string vulnerability",
  "7.2 Integer overflow",
  "7.2 TOCTOU race condition",
  "7.2 Command injection",
  "7.2 LDAP injection",
  "7.2 XXE attacks",
  "7.2 SSRF",
  "7.2 Open redirect",
  "7.2 IDOR",
  "7.2 Deserialization attack",
  "7.2 CORS misconfiguration",
  "7.2 JWT 'none' algorithm vulnerability",
  "7.2 Session fixation",
  "7.2 Clickjacking",
  "7.2 HSTS",
  "7.2 Subresource Integrity",
  "7.3 Jailbreak/root detection",
  "7.3 Mobile app sandboxing",
  "7.3 Mobile permissions model",
  "7.3 COPE vs BYOD vs COBO",
  "7.4 Container escape",
  "7.4 Kubernetes RBAC",
  "7.4 Container secrets management",
  "7.5 ICS / SCADA basics",
  "7.5 Embedded device firmware updates"
];
