// CompTIA Data+ (DA0-002) sub-objective tag per question, in the same order as questions.js.
// Aligned to the official DA0-002 exam objectives:
//   1.1 Data concepts | 1.2 Data sources | 1.3 Infrastructure | 1.4 Tools | 1.5 AI concepts
//   2.1 Acquisition | 2.2 Exploration | 2.3 Transformation
//   3.1 Communicate results | 3.2 Statistical methods | 3.3 Troubleshoot
//   4.1 Create visuals | 4.2 Deliver reports | 4.3 Validate reporting
//   5.1 Management practices | 5.2 Compliance | 5.3 Privacy/protection | 5.4 Quality assurance
window.TOPICS = [
  "1.1 Data types - structured",
  "1.1 Data types - unstructured",
  "1.1 Data types - semi-structured",
  "1.1 File formats - CSV",
  "1.1 File formats - JSON",
  "1.1 File formats - XML",
  "1.1 File formats - Parquet",
  "1.1 File formats - Avro",
  "1.1 Database types - RDBMS",
  "1.1 Database types - document NoSQL",
  "1.1 Database types - key-value",
  "1.1 Database types - graph",
  "1.1 Database types - columnar",
  "1.1 OLTP characteristics",
  "1.1 OLAP characteristics",
  "1.1 OLTP vs OLAP",
  "1.2 Data warehouse as source",
  "1.2 Data lake as source",
  "1.2 Data lakehouse",
  "1.2 Data mart",
  "1.2 ETL process",
  "1.2 ELT process",
  "1.2 ETL vs ELT",
  "1.1 Star schema",
  "1.1 Snowflake schema",
  "1.1 First Normal Form",
  "1.1 Second Normal Form",
  "1.1 Third Normal Form",
  "1.1 Denormalization",
  "1.3 Cloud DW - Snowflake",
  "1.3 Cloud DW - BigQuery",
  "1.3 Cloud DW - Redshift",
  "1.3 Object storage",
  "1.3 File vs object storage",
  "1.1 Master data management",
  "1.1 Reference data",
  "1.2 Batch vs stream processing",
  "1.2 Data pipeline basics",
  "1.1 Primary keys",
  "1.1 Foreign keys",
  "1.1 Indexes",
  "1.1 Time-series data",
  "2.1 Batch ingestion",
  "2.1 Stream ingestion",
  "2.1 Change Data Capture",
  "2.1 API ingestion",
  "2.1 Webhook ingestion",
  "2.1 Web scraping considerations",
  "2.1 Event-driven file ingestion",
  "2.1 Message queues",
  "2.1 Pull vs push ingestion",
  "2.1 Source system impact",
  "2.1 ETL tools",
  "2.1 Idempotent operations",
  "2.1 Pipeline orchestration",
  "2.1 Incremental vs full load",
  "2.1 Backfilling",
  "2.2 Missing value detection",
  "2.3 Mean imputation",
  "2.3 Median imputation",
  "2.3 Mode imputation",
  "2.3 K-NN imputation",
  "2.2 Outlier definition",
  "2.2 IQR outlier rule",
  "2.2 Z-score outlier rule",
  "2.2 Deduplication",
  "2.2 Data validation rules",
  "2.3 Type conversion",
  "2.3 Standardization",
  "2.3 Min-max normalization",
  "2.3 One-hot encoding",
  "2.3 Label encoding",
  "2.3 Ordinal encoding",
  "2.3 Inner join",
  "2.3 Left outer join",
  "2.3 Full outer join",
  "2.3 Cross join",
  "2.3 UNION",
  "2.3 INTERSECT",
  "2.3 EXCEPT",
  "2.3 Pivot",
  "2.3 Unpivot",
  "2.2 Data profiling output",
  "2.1 Simple random sampling",
  "2.1 Stratified sampling",
  "2.1 Systematic sampling",
  "2.1 Cluster sampling",
  "2.2 Convenience sampling risk",
  "2.3 Data cleansing scope",
  "2.3 Feature engineering",
  "2.3 Binning",
  "2.1 Sample size considerations",
  "2.3 Format standardization",
  "2.3 Aggregation",
  "2.2 Schema enforcement",
  "2.2 Data quality SLA",
  "2.1 Stratified split for ML",
  "3.2 Mean",
  "3.2 Median",
  "3.2 Mode",
  "3.2 Range",
  "3.2 Variance",
  "3.2 Standard deviation",
  "3.2 Quartiles",
  "3.2 IQR",
  "3.2 Skewness - right",
  "3.2 Skewness - left",
  "3.2 Normal distribution",
  "3.2 Empirical rule (68-95-99.7)",
  "3.2 Kurtosis",
  "3.2 Population vs sample",
  "3.2 Mean vs median for income",
  "3.2 Discrete distributions",
  "3.2 Poisson distribution",
  "3.2 Uniform distribution",
  "3.2 Bernoulli trial",
  "3.2 Central limit theorem",
  "3.2 Z-score",
  "3.2 Independent event probability",
  "3.2 Conditional probability",
  "3.2 Null hypothesis",
  "3.2 Alternative hypothesis",
  "3.2 p-value",
  "3.2 Significance level alpha",
  "3.3 Type I error",
  "3.3 Type II error",
  "3.2 Confidence interval",
  "3.2 Statistical power",
  "3.2 Effect size",
  "3.2 Pearson correlation",
  "3.2 Pearson r range",
  "3.2 Spearman correlation",
  "3.3 Correlation vs causation",
  "3.2 Linear regression",
  "3.2 Multiple regression",
  "3.2 R-squared",
  "3.2 Residual",
  "3.2 Logistic regression",
  "3.3 Overfitting",
  "3.3 Underfitting",
  "3.2 Supervised vs unsupervised",
  "3.2 Classification vs regression",
  "3.2 Clustering",
  "3.2 K-means",
  "3.2 Decision tree",
  "3.2 Random forest",
  "3.2 A/B testing purpose",
  "3.2 A/B test significance",
  "3.2 A/B test sample size",
  "3.1 Descriptive analytics",
  "3.1 Diagnostic analytics",
  "3.1 Predictive analytics",
  "3.1 Prescriptive analytics",
  "3.3 Survivorship bias",
  "3.3 Confounding variables",
  "4.1 Bar chart use",
  "4.1 Line chart use",
  "4.1 Pie chart limitations",
  "4.1 Scatter plot use",
  "4.1 Histogram purpose",
  "4.1 Box plot information",
  "4.1 Heatmap use",
  "4.1 Treemap purpose",
  "4.1 Sankey diagram",
  "4.1 Funnel chart",
  "4.1 Choropleth map",
  "4.1 Area vs line chart",
  "4.1 Stacked bar pitfall",
  "4.1 100% stacked bar",
  "4.1 Bullet chart",
  "4.1 Pareto chart",
  "4.1 Sparkline",
  "4.1 Word cloud limitations",
  "4.2 Dashboard purpose",
  "4.2 Operational vs strategic dashboard",
  "4.2 KPI definition",
  "4.2 Audience-driven dashboard",
  "4.2 Dashboard refresh rate",
  "4.2 Dashboard filters",
  "4.2 Drill-down vs drill-through",
  "4.2 Cross-filtering",
  "4.1 Color blindness",
  "4.1 Data-ink ratio",
  "4.1 Chart junk",
  "4.3 Truncated y-axis",
  "4.3 Dual-axis pitfall",
  "4.3 3D chart pitfall",
  "4.3 Cherry-picked range",
  "4.3 Improper aggregation",
  "4.3 Bubble sizing pitfall",
  "4.3 Misleading color scale",
  "4.2 Tableau platform",
  "4.2 Power BI platform",
  "4.2 Looker platform",
  "4.2 Qlik platform",
  "4.2 Open-source viz libraries",
  "4.2 Self-service BI",
  "4.1 Storytelling with data",
  "4.1 Audience-first viz",
  "4.1 Chart annotations",
  "4.1 Title best practice",
  "4.1 Pre-attentive attributes",
  "4.2 Static vs interactive dashboard",
  "4.2 Operational metric example",
  "4.2 Strategic metric example",
  "4.1 Multi-line time series",
  "4.1 Small multiples",
  "4.2 Pre-aggregated data trade-offs",
  "4.3 Sample size disclosure",
  "4.3 Y-axis truncation example",
  "4.3 Mixed-units axis",
  "5.4 Data quality - accuracy",
  "5.4 Data quality - completeness",
  "5.4 Data quality - consistency",
  "5.4 Data quality - timeliness",
  "5.4 Data quality - validity",
  "5.4 Data quality - uniqueness",
  "5.4 Data quality - integrity",
  "5.4 Data profiling vs cleansing",
  "5.1 Data lineage",
  "5.1 Data catalog",
  "5.1 Data steward role",
  "5.1 Data owner role",
  "5.1 Data custodian role",
  "5.1 Metadata - business",
  "5.1 Metadata - technical",
  "5.1 Metadata - operational",
  "5.3 PII definition",
  "5.3 PHI vs PII",
  "5.3 PCI cardholder data",
  "5.2 GDPR scope",
  "5.3 GDPR data subject rights",
  "5.2 CCPA scope",
  "5.2 HIPAA scope",
  "5.3 Right to erasure limitations",
  "5.3 Data minimization",
  "5.3 Purpose limitation",
  "5.3 GDPR consent",
  "5.3 Data anonymization",
  "5.3 Pseudonymization",
  "5.3 Data masking",
  "5.3 Tokenization",
  "5.2 Cross-border data transfer",
  "5.2 Residency vs sovereignty",
  "5.2 Retention policy",
  "5.2 GDPR breach notification timing",
  "5.3 Audit logging",
  "5.3 Privacy by design",
  "1.5 AI vs ML distinction",
  "1.5 Generative vs predictive AI",
  "1.5 Large language models",
  "1.5 Natural Language Processing",
  "1.5 NLP task - sentiment analysis",
  "1.5 NLP task - named entity recognition",
  "1.5 Robotic Process Automation",
  "1.5 RPA vs traditional automation",
  "1.5 AI bias source",
  "1.5 AI explainability",
  "1.5 AI hallucination",
  "1.5 AI training vs inference",
  "1.5 Prompt engineering",
  "1.5 Retrieval-augmented generation",
  "1.5 AI ethics consideration",
  "3.3 Multicollinearity in regression",
  "3.3 Garbage in, garbage out"
];
