// Discrete Mathematics sub-objective tag per question, in the same order as questions.js.
// Areas: 1 Logic, 2 Sets, 3 Functions/Relations, 4 Counting, 5 Graphs, 6 Number Theory.
window.TOPICS = [
  "1.1 Proposition definition",
  "1.1 Implication truth value",
  "1.1 Biconditional truth",
  "1.2 Tautology definition",
  "1.2 De Morgan's for logic",
  "1.2 Contrapositive",
  "1.2 Converse",
  "1.2 Inverse",
  "1.3 Universal quantifier",
  "1.3 Existential quantifier",
  "1.3 Negating a universal",
  "1.3 Negating an existential",
  "1.4 Modus ponens",
  "1.4 Modus tollens",
  "1.5 Proof by contradiction",
  "1.5 Proof by contrapositive",
  "1.5 Mathematical induction structure",
  "1.5 Counterexample purpose",
  "2.1 Set membership notation",
  "2.1 Subset definition",
  "2.1 Proper subset",
  "2.2 Union definition",
  "2.2 Intersection definition",
  "2.2 Set difference",
  "2.3 Cartesian product cardinality",
  "2.3 Power set cardinality",
  "2.3 Power set example",
  "2.4 Empty set subset",
  "2.4 De Morgan's for sets",
  "2.5 Inclusion-exclusion (2 sets)",
  "2.6 Countable sets",
  "2.6 Uncountable sets",
  "3.1 Relation definition",
  "3.2 Reflexive relation",
  "3.2 Symmetric relation",
  "3.2 Transitive relation",
  "3.2 Antisymmetric relation",
  "3.3 Equivalence relation",
  "3.3 Equivalence class",
  "3.3 Congruence mod n",
  "3.4 Partial order",
  "3.4 Total order",
  "3.5 Function definition",
  "3.5 Domain definition",
  "3.5 Codomain vs range",
  "3.6 Injective definition",
  "3.6 Surjective definition",
  "3.6 Bijective definition",
  "3.6 Injective real example",
  "3.6 Surjective real example",
  "3.7 Function composition",
  "3.7 Composition order matters",
  "3.7 Identity function",
  "3.8 Inverse function existence",
  "3.8 Inverse computation",
  "3.9 Floor function",
  "3.9 Ceiling function",
  "4.1 Sum rule",
  "4.1 Product rule",
  "4.2 Permutation formula",
  "4.2 Permutation P(n,r)",
  "4.3 Combination formula",
  "4.3 Combination calculation",
  "4.3 Permutation vs combination distinction",
  "4.4 Combinations with repetition formula",
  "4.4 Permutations with repetition",
  "4.5 Pigeonhole principle",
  "4.5 Pigeonhole application",
  "4.6 Inclusion-exclusion (2 sets)",
  "4.6 Inclusion-exclusion (3 sets)",
  "4.7 Binomial coefficient definition",
  "4.7 Pascal's rule",
  "4.7 Sum of binomial coefficients",
  "4.8 Stars and bars",
  "4.8 Multinomial coefficient",
  "5.1 Graph definition",
  "5.2 Degree of a vertex",
  "5.2 Handshake lemma",
  "5.3 Complete graph K_n",
  "5.3 Bipartite graph",
  "5.4 Path and cycle",
  "5.4 Connected graph",
  "5.5 Tree definition",
  "5.5 Tree edge count",
  "5.6 Eulerian circuit",
  "5.6 Eulerian path condition",
  "5.7 Hamiltonian cycle",
  "5.8 Graph isomorphism",
  "6.1 Divisibility notation",
  "6.1 Prime definition",
  "6.2 GCD definition",
  "6.2 GCD example",
  "6.2 LCM relationship",
  "6.3 Euclidean algorithm",
  "6.4 Modular arithmetic",
  "6.4 Congruence definition",
  "6.4 Congruence example",
  "6.5 Fundamental theorem of arithmetic",
  "6.6 Binary representation",
  "6.6 Hexadecimal representation"
];
