// CCSP sub-objective tag per question, in the same order as questions.js.
// IDs follow the standard CCSP CBK domain/sub-objective structure (best-effort
// mapping — adjust freely if your practice-exam tool uses a different outline).
window.TOPICS = [
  "1.1 Cloud computing concepts (NIST characteristics)",
  "1.1 Cloud service models (IaaS/PaaS/SaaS)",
  "1.1 Cloud deployment models",
  "1.2 Shared responsibility model",
  "1.1 NIST essential characteristics",
  "1.3 Multi-tenancy security concerns",
  "1.1 Rapid elasticity",
  "1.1 PaaS responsibilities",
  "1.1 Hybrid cloud / cloud bursting",
  "1.4 Vendor lock-in / portability",
  "1.2 Cloud reference architecture - actors",
  "1.3 Cryptography - AES",
  "1.3 Cryptography - key length",
  "1.3 Cryptography - hash function properties",
  "1.3 Cryptography - digital signatures",
  "1.5 CSA STAR",
  "1.5 FedRAMP",
  "1.5 ISO/IEC 27017 / 27018",
  "1.5 SOC reports",
  "1.4 Portability",
  "1.4 Interoperability",
  "1.4 Reversibility",
  "1.4 Defense in depth",
  "1.4 Zero trust",
  "1.1 Cloud economics (CapEx vs OpEx)",
  "1.2 Cloud actors - auditor",
  "1.3 Cryptography - PKI",
  "1.1 Measured service",
  "1.1 Private cloud characteristics",
  "1.2 Cloud carrier role",
  "1.4 Functional vs non-functional requirements",
  "1.4 High availability design",
  "1.4 Least privilege",
  "1.1 IaaS vs PaaS responsibility split",
  "1.2 Cloud reference architecture purpose",
  "1.1 Cloud computing advantages and limits",
  "1.3 Cryptography - asymmetric",
  "1.2 Shared responsibility model",
  "1.1 Broad network access",
  "1.3 Multi-tenancy security concerns",
  "1.4 Functional vs non-functional requirements",
  "1.3 Cryptography - salt for password hashing",

  "2.1 Cloud secure data lifecycle phases",
  "2.5 Data classification timing",
  "2.2 Object storage",
  "2.2 Block / volume storage",
  "2.2 File storage",
  "2.2 Ephemeral storage",
  "2.3 Key management - BYOK",
  "2.3 Key management - HYOK",
  "2.3 Hardware Security Modules",
  "2.3 Tokenization",
  "2.3 Anonymization",
  "2.3 Dynamic data masking",
  "2.3 Data Loss Prevention - data in motion",
  "2.6 Information Rights Management",
  "2.7 Crypto-shredding",
  "2.7 Cloud data destruction",
  "2.3 Homomorphic encryption",
  "2.5 Data classification policy",
  "2.1 Structured vs unstructured data",
  "2.7 Data retention policies",
  "2.7 Legal hold",
  "2.7 Immutable / WORM storage",
  "2.2 Object versioning",
  "2.3 Data dispersion / bit splitting",
  "2.3 Tokenization vs encryption",
  "2.3 Encryption at rest",
  "2.3 Endpoint DLP",
  "2.3 Confidential computing / TEE",
  "2.3 TLS - data in transit",
  "2.8 Storage access logging",
  "2.4 Data discovery",
  "2.3 Client-side encryption / customer-controlled keys",
  "2.3 Data integrity via hashing",
  "2.3 Key Management Service benefits",
  "2.3 Pseudonymization under GDPR",
  "2.7 Archive encryption key lifecycle",
  "2.1 Data lifecycle - Share phase",
  "2.3 Customer-controlled key release",
  "2.7 Cloud media sanitization",
  "2.5 Classification metadata and labeling",
  "2.1 Data sovereignty",
  "2.3 Envelope encryption (DEK/KEK)",
  "2.8 Audit logging for data destruction",
  "2.6 IRM use cases",
  "2.3 Network DLP",
  "2.3 Searchable encryption / tokenization",
  "2.7 Ransomware resilience",
  "2.7 Data remanence",
  "2.1 Data residency / region restrictions",
  "2.5 Data governance program",
  "2.3 Format-preserving encryption",
  "2.7 Archival considerations",
  "2.1 Data lifecycle - Use phase",
  "2.8 Object-level access logging",
  "2.3 Tokenization for PCI scope reduction",
  "2.3 Cryptographic salt",
  "2.5 Establishing data classification program",

  "3.1 Hypervisors (Type 1 vs Type 2)",
  "3.3 VM escape",
  "3.3 Hyperjacking",
  "3.4 Microsegmentation",
  "3.4 East-west vs north-south traffic",
  "3.1 Software-defined networking",
  "3.1 Trusted Platform Module",
  "3.4 Secure Boot",
  "3.4 Bastion / jump host",
  "3.5 BCDR - hot site",
  "3.5 RTO",
  "3.5 RPO",
  "3.5 MTD",
  "3.3 Multi-tenancy threats / side-channel",
  "3.4 Container image and supply chain security",
  "3.4 CSPM",
  "3.4 CWPP",
  "3.4 CASB",
  "3.4 Identity federation",
  "3.4 Privileged Access Management",
  "3.4 Just-in-time access",
  "3.4 Web Application Firewalls",
  "3.4 IDS vs IPS",
  "3.4 Honeypots",
  "3.4 Hypervisor patching",
  "3.4 Hypervisor zero-day response",
  "3.2 Data center Tier ratings",
  "3.4 Network segmentation",
  "3.4 Blast radius",
  "3.1 Network Function Virtualization",
  "3.3 Side-channel attacks",
  "3.4 Trusted Execution Environments",
  "3.4 Cloud admin account compromise mitigations",
  "3.4 VM sprawl controls",
  "3.4 VPC network ACLs",
  "3.5 BCDR - cold site",
  "3.5 DRaaS",
  "3.4 Lateral movement prevention",
  "3.1 IaaS responsibility split",
  "3.4 Cloud landing zone",

  "4.2 Secure SDLC phases / threat modeling",
  "4.3 STRIDE threat modeling",
  "4.3 OWASP Top 10 - Broken Access Control",
  "4.3 OWASP Top 10 - Injection",
  "4.5 OWASP Top 10 - Vulnerable components",
  "4.3 OWASP Top 10 - Insecure Design",
  "4.4 SAST",
  "4.4 DAST",
  "4.4 IAST",
  "4.6 RASP",
  "4.5 Software Bill of Materials (SBOM)",
  "4.3 DevSecOps / CI/CD security",
  "4.7 OAuth 2.0",
  "4.7 OpenID Connect",
  "4.7 SAML 2.0",
  "4.7 SCIM provisioning",
  "4.7 Attribute-Based Access Control",
  "4.7 Role-Based Access Control",
  "4.3 XSS defenses",
  "4.3 CSRF defenses",
  "4.6 API rate limiting",
  "4.6 BOLA / API access control",
  "4.6 Secrets management",
  "4.6 API gateways",
  "4.5 Container image signing",
  "4.4 Penetration testing",
  "4.4 Cloud pen testing authorization",
  "4.6 Microservices security",
  "4.6 Service mesh",
  "4.6 Serverless / FaaS security",
  "4.3 Injection defenses - parameterized queries",
  "4.7 Multi-factor authentication",
  "4.3 OWASP Top 10 - SSRF",
  "4.2 Shift left",
  "4.7 Federation risk",
  "4.7 OAuth scope management",
  "4.5 Secret scanning",
  "4.7 BYOI risks",

  "5.6 SIEM",
  "5.6 SOAR",
  "5.6 UEBA",
  "5.6 NIST IR lifecycle",
  "5.6 Post-incident activity",
  "5.4 Cloud forensics challenges",
  "5.4 Chain of custody",
  "5.4 Order of volatility",
  "5.4 eDiscovery",
  "5.3 Vulnerability management",
  "5.3 Patch management",
  "5.3 Change management",
  "5.3 Standard / pre-approved changes",
  "5.3 Tabletop exercises",
  "5.3 BCDR testing",
  "5.6 Continuous monitoring",
  "5.6 Cloud audit logs",
  "5.6 Threat hunting",
  "5.6 EDR",
  "5.3 CMDB and configuration management",
  "5.2 Backup management (3-2-1)",
  "5.2 Backup restore testing",
  "5.3 BCP vs DRP",
  "5.5 Provider coordination during IR",
  "5.6 MTTD",
  "5.6 MTTR",
  "5.2 Immutable infrastructure",
  "5.6 Log retention",
  "5.6 Anomaly-based detection",
  "5.3 BCDR test types",
  "5.3 Access reviews and recertification",
  "5.6 Red team / purple team exercises",
  "5.4 Cloud-specific forensic challenges (ephemerality)",
  "5.4 Cloud evidence preservation",
  "5.6 SOC effectiveness metrics",
  "5.6 Detection engineering",
  "5.6 Insider threat mitigations",
  "5.6 Privileged account anomaly response",
  "5.4 Forensic image integrity",
  "5.5 Incident communication strategy",

  "6.2 GDPR - controller vs processor",
  "6.2 GDPR - breach notification timing",
  "6.2 GDPR - right to erasure",
  "6.2 GDPR - DPIA",
  "6.1 HIPAA",
  "6.1 PCI DSS",
  "6.1 SOX",
  "6.2 CCPA / CPRA",
  "6.1 Cloud eDiscovery challenges",
  "6.5 SLA",
  "6.5 Master Service Agreement",
  "6.3 Independent audits and certifications",
  "6.4 Risk transference - insurance",
  "6.4 Residual risk",
  "6.4 Quantitative risk analysis",
  "6.4 NIST Risk Management Framework",
  "6.4 ISO 31000",
  "6.2 Privacy by design",
  "6.2 Cross-border data transfer (SCC/BCR)",
  "6.1 Data localization requirements",
  "6.5 Vendor management lifecycle",
  "6.5 Subcontractor / sub-processor risk",
  "6.3 SOC 1 audit reports",
  "6.3 SOC 2 Type I vs Type II",
  "6.5 Vendor risk assessment",
  "6.3 Compliance gap analysis",
  "6.1 Cross-jurisdictional forensics",
  "6.5 SLA metrics and remedies",
  "6.3 Compensating controls",
  "6.4 Risk acceptance",
  "6.5 Provider change-control / exit provisions",
  "6.5 Sub-processor flow-down clauses",
  "6.3 Control inheritance (FedRAMP)",
  "6.5 Right-to-audit clauses",
  "6.1 Jurisdiction in cloud forensics",
  "6.2 Data Protection Officer (DPO)"
];
