// LPI Linux Essentials sub-objective tag per question, in the same order as questions.js.
// IDs follow the LPI 010-160 exam objective structure.
window.TOPICS = [
  "1.1 Linux kernel origin",
  "1.1 Kernel vs operating system",
  "1.1 Common Linux license",
  "1.1 Debian-based distributions",
  "1.1 Enterprise distributions",
  "1.1 Rolling release",
  "1.1 LTS meaning",
  "1.1 Kernel role",
  "1.4 Major desktop environments",
  "1.2 Common Linux web browser",
  "1.2 Common Linux office suite",
  "1.2 Common Linux web server",
  "1.2 Common Linux RDBMS",
  "1.2 Common version control",
  "1.3 Free software vs open source",
  "1.3 GPL copyleft",
  "1.3 Permissive licenses",
  "1.3 Apache License feature",
  "1.3 Dual licensing",
  "1.1 Android and Linux",
  "1.1 Linux on supercomputers",
  "1.4 Default Linux shell",
  "1.2 Common image editor",
  "1.2 Common media player",
  "1.4 Common terminal text editors",
  "2.1 Shell definition",
  "2.1 PATH variable",
  "2.1 Echo command",
  "2.1 Single vs double quotes",
  "2.1 Command substitution",
  "2.1 env command",
  "2.1 alias command",
  "2.1 .bashrc file",
  "2.1 Tab completion",
  "2.1 Command history",
  "2.1 !! shortcut",
  "2.1 Ctrl-C behavior",
  "2.1 Ctrl-D in shell",
  "2.1 Setting an env var",
  "2.1 Clearing the screen",
  "2.2 man command",
  "2.2 man section for system calls",
  "2.2 man section for user commands",
  "2.2 apropos command",
  "2.2 whatis command",
  "2.2 --help convention",
  "2.2 info command",
  "2.2 which command",
  "2.2 whereis command",
  "2.2 type command",
  "2.2 Help for shell built-ins",
  "2.2 /usr/share/doc",
  "2.2 man -k vs apropos",
  "2.2 man synopsis brackets",
  "2.2 Multiple manual sections",
  "2.3 pwd command",
  "2.3 cd no arguments",
  "2.3 cd - shortcut",
  "2.3 ls long listing",
  "2.3 ls hidden files",
  "2.3 ls human-readable sizes",
  "2.3 ls recursive",
  "2.3 ls sort by time",
  "2.3 Absolute path",
  "2.3 Tilde expansion",
  "2.3 /etc directory",
  "2.3 /home directory",
  "2.3 /var directory",
  "2.3 /tmp directory",
  "2.3 /usr/bin directory",
  "2.3 Parent directory shortcut",
  "2.4 cp command",
  "2.4 mv command",
  "2.4 rm command",
  "2.4 rm recursive",
  "2.4 rm -f",
  "2.4 mkdir command",
  "2.4 mkdir -p",
  "2.4 rmdir limitation",
  "2.4 touch command",
  "2.4 Hard link",
  "2.4 Symbolic link",
  "2.4 ln -s syntax",
  "2.4 Star wildcard",
  "2.4 Question mark wildcard",
  "2.4 Character class glob",
  "2.4 cp recursive",
  "3.1 tar create archive",
  "3.1 tar extract archive",
  "3.1 tar list contents",
  "3.1 tar gzip create",
  "3.1 tar gzip extract",
  "3.1 tar bzip2 option",
  "3.1 tar xz option",
  "3.1 gzip command",
  "3.1 gunzip command",
  "3.1 bzip2 command",
  "3.1 xz command",
  "3.1 zip command",
  "3.1 unzip command",
  "3.1 tar.gz vs tgz",
  "3.1 dd command purpose",
  "3.2 cat command",
  "3.2 head command",
  "3.2 tail command",
  "3.2 tail -f",
  "3.2 less command",
  "3.2 grep basics",
  "3.2 grep case insensitive",
  "3.2 grep invert match",
  "3.2 grep recursive",
  "3.2 grep line numbers",
  "3.2 grep extended regex",
  "3.2 sort command",
  "3.2 sort numeric",
  "3.2 sort reverse",
  "3.2 uniq command",
  "3.2 uniq count",
  "3.2 wc line count",
  "3.2 wc word count",
  "3.2 cut command",
  "3.2 tr command",
  "3.2 sed substitution",
  "3.2 awk field reference",
  "3.2 find command",
  "3.2 find by name",
  "3.2 find by type",
  "3.3 Shebang line",
  "3.3 Script executable",
  "3.3 Variable assignment",
  "3.3 Variable reference",
  "3.3 Command substitution preferred",
  "3.3 if-then-else syntax",
  "3.3 Test command",
  "3.3 for loop syntax",
  "3.3 while loop syntax",
  "3.3 Exit code success",
  "3.3 $? variable",
  "3.3 Positional parameters",
  "3.3 Argument count",
  "3.3 All arguments",
  "3.3 read command",
  "4.1 Linux on cloud",
  "4.1 Embedded Linux",
  "4.1 Beginner-friendly distribution",
  "4.1 Server distributions",
  "4.1 Router distribution",
  "4.1 Linux on TOP500",
  "4.1 Choosing by package manager",
  "4.1 Choosing by package manager Red Hat",
  "4.1 Stable vs rolling tradeoffs",
  "4.1 LTS choice",
  "4.2 lspci command",
  "4.2 lsusb command",
  "4.2 lsblk command",
  "4.2 dmesg command",
  "4.2 cpuinfo path",
  "4.2 meminfo path",
  "4.2 lscpu command",
  "4.2 lshw command",
  "4.2 Module load command",
  "4.2 /sys filesystem",
  "4.3 /etc contents",
  "4.3 /home location",
  "4.3 /var/log location",
  "4.3 /tmp behavior",
  "4.3 /usr/bin vs /bin",
  "4.3 /sbin purpose",
  "4.3 /boot directory",
  "4.3 ps command",
  "4.3 top vs htop",
  "4.3 kill default signal",
  "4.3 kill -9 effect",
  "4.3 df command",
  "4.3 du command",
  "4.3 free command",
  "4.3 mount command",
  "4.4 ping command",
  "4.4 traceroute command",
  "4.4 ip addr show",
  "4.4 ifconfig legacy",
  "4.4 ss command",
  "4.4 /etc/hosts purpose",
  "4.4 /etc/resolv.conf",
  "4.4 ssh basic syntax",
  "4.4 wget vs curl",
  "4.4 DNS lookup tools",
  "4.4 SSH default port",
  "4.4 ip route",
  "4.4 DHCP client",
  "4.4 hostname command",
  "4.4 Default gateway purpose",
  "5.1 root UID",
  "5.1 Regular user UID range",
  "5.1 /etc/passwd contents",
  "5.1 /etc/shadow contents",
  "5.1 sudo purpose",
  "5.1 su command",
  "5.1 who command",
  "5.1 w command",
  "5.1 id command",
  "5.1 last command",
  "5.1 /etc/sudoers",
  "5.1 System user UID range",
  "5.2 useradd command",
  "5.2 usermod command",
  "5.2 userdel command",
  "5.2 passwd command",
  "5.2 groupadd command",
  "5.2 groupmod command",
  "5.2 groupdel command",
  "5.2 /etc/passwd field order",
  "5.2 /etc/shadow field one",
  "5.2 Primary vs secondary group",
  "5.2 gpasswd command",
  "5.2 UID 0 significance",
  "5.2 Default shell config",
  "5.2 /etc/skel directory",
  "5.3 chmod 755 meaning",
  "5.3 chmod 644 meaning",
  "5.3 chmod u+x",
  "5.3 chmod g-w",
  "5.3 chmod o+r",
  "5.3 chmod a+x",
  "5.3 chown user:group",
  "5.3 chgrp command",
  "5.3 umask purpose",
  "5.3 Common default umask",
  "5.3 rwx on file",
  "5.3 rwx on directory",
  "5.3 ls -l first character",
  "5.3 Permission triple meaning",
  "5.3 Octal permission digits",
  "5.3 chmod recursive",
  "5.3 Directory enter requires x",
  "5.3 Directory listing requires r",
  "5.3 Directory create requires w",
  "5.3 Default ownership of new files",
  "5.4 SUID purpose",
  "5.4 SGID on files",
  "5.4 SGID on directories",
  "5.4 Sticky bit purpose",
  "5.4 Sticky bit on /tmp",
  "5.4 SUID octal prefix",
  "5.4 SGID octal prefix",
  "5.4 Sticky octal prefix",
  "5.4 /tmp permissions",
  "5.4 passwd command SUID",
  "5.4 chmod 4755 result",
  "5.4 chmod 2775 result"
];
